version: '3.8'

services:
  davis-hotel:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=your-production-jwt-secret-change-this
    volumes:
      - ./server/database:/app/database
      - ./server/uploads:/app/uploads
    restart: unless-stopped

  # Optional: Add a reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - davis-hotel
    restart: unless-stopped