[build]
  publish = "client/build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://davis-hotel-api.herokuapp.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://davis-hotel-api.herokuapp.com"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://davis-hotel-api.herokuapp.com"